using System;
using System.IO;
using System.IO.Pipes;
using System.Diagnostics;
using System.Threading;

namespace MonoTests.System.IO.Pipes
{
  public class T112_Client : PipeTestWrapper
  {
    public static int Main(string[] arguments) {
      return new T112_Client().Execute(arguments);
    }

    public override string TestDescription {
      get {
        return @"Attempt to creates an (IN) anonymous pipe client stream from 
                 the handle passed on the commandline and then throw an error
                 if the specified handle exists.";
      }
    }

    protected override void DoTest(string[] arguments)
    {
      InheritedContextSwitchTool();
      string inHandle = null;
      foreach (string arg in arguments)
      {
        if (arg.StartsWith("/inHandle:")) {
          inHandle = arg.Substring("/inHandle:".Length);
        }
      }
      if (inHandle == null) {
        _log.Error("Usage: /inHandle:<pipehandle>");
        _log.Error("  inHandle - handle generated by GetClientHandleAsString() which will be read from");
        return;
      }

      _log.Test("Setting up streams");
      _log.Info("Received in handle {0}", inHandle);

      try {
        using (AnonymousPipeClientStream pipeClientIn = new AnonymousPipeClientStream(PipeDirection.In, inHandle))
        {
          _log.Error("Never should reach this point");
        }
      } catch (IOException eError) {
        if (eError.Message != "Unable to load pipe with error code ERROR_INVALID_HANDLE") {
          _log.Error(eError, "Unexpected io exception");
        } else {
          _log.Test("Received expect exception");
        }
      }
      _log.Test("Done disposing pipe streams");
    }
  }
}
